human_energy_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_HOST', 'postgres-dwh') }}"
      port: "{{ env_var('DBT_PORT', '5432') | as_number }}"
      user: "{{ env_var('DBT_USER', 'airflow') }}"
      pass: "{{ env_var('DBT_PASSWORD', 'airflow') }}"
      dbname: "{{ env_var('DBT_DATABASE', 'dwh') }}"
      schema: "{{ env_var('DBT_SCHEMA', 'public') }}"
      threads: 4 