name: 'human_energy_project'
version: '1.0.0'
config-version: 2

profile: 'human_energy_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  human_energy_project:
    # Config for all models in the project
    +materialized: table
    staging:
      +materialized: view
    marts:
      +materialized: table 